### ISSUE TITLE
🐞 [Bug]: Unable to resolve action `restqa/404-links@v2.2.0`, unable to find version `v2.2.0`

### ISSUE THREAD

**Issue by tifa365** [restqa/404-links#28]
### What happened?

While running this job, I receive the following error

`Unable to resolve action `restqa/404-links@v2.2.0`, unable to find version `v2.2.0``
```

name: check links

on: [push]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'restqa-404-links'
      uses: restqa/404-links@v2.2.0
```

### Relevant log output

```shell
Annotations
1 error
check-links
Unable to resolve action `restqa/404-links@v2.2.0`, unable to find version `v2.2.0`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
